name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
       -  name: Set execute permission for wdio
          run: chmod +x ./node_modules/.bin/wdio

        - name: Run tests
          run: ./node_modules/.bin/wdio wdio.conf.js

  
