name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Add WebdriverIO to PATH
          run: echo "::add-path::$(pwd)/node_modules/.bin"
        - name: Test
          run: npm run wdio
        
